"""Generate both SDK operation tables and schemas from the running FastAPI contract.

    python scripts/generate_contract.py           write the generated files
    python scripts/generate_contract.py --check   exit 1 when a committed file is stale

`sdk/typescript/src/schema.ts` comes from contracts/openapi.json through openapi-typescript
(`npm run generate --prefix sdk/typescript`); CI checks it the same way."""

from __future__ import annotations

import argparse
import difflib
import json
import sys
import tempfile
from pathlib import Path

from eventmem.core.api import create_app

ROOT = Path(__file__).resolve().parents[1]
GENERATED = (
    "contracts/openapi.json",
    "src/eventmem/sdk/_operations.py",
    "src/eventmem/sdk/_types.py",
    "src/eventmem/sdk/__init__.pyi",
    "sdk/typescript/src/operations.ts",
)


def generate(root: Path):
    with tempfile.TemporaryDirectory() as temp:
        schema = create_app(
            temp, token="contract-generation-only", workers=False, mcp_enabled=False
        ).openapi()
    destination = root / "contracts"
    destination.mkdir(parents=True, exist_ok=True)
    (destination / "openapi.json").write_text(
        json.dumps(schema, ensure_ascii=False, indent=2) + "\n"
    )
    operations = {}
    for path, methods in schema["paths"].items():
        for method, operation in methods.items():
            if "operationId" in operation:
                operations[operation["operationId"]] = {
                    "method": method.upper(),
                    "path": path,
                    "parameters": operation.get("parameters", []),
                    "body": operation.get("requestBody", {}),
                }
    py = (
        "# Generated by scripts/generate_contract.py; do not edit.\nOPERATIONS = "
        + repr(operations)
        + "\n"
    )
    sdk = root / "src/eventmem/sdk"
    sdk.mkdir(parents=True, exist_ok=True)
    (sdk / "_operations.py").write_text(py)
    ts = root / "sdk/typescript/src"
    ts.mkdir(parents=True, exist_ok=True)
    (ts / "operations.ts").write_text(
        "// Generated by scripts/generate_contract.py; do not edit.\nexport const operations = "
        + json.dumps(operations, ensure_ascii=False, indent=2)
        + " as const;\nexport type Operation = keyof typeof operations;\n"
    )
    here = str(Path(__file__).resolve().parent)
    if here not in sys.path:
        sys.path.insert(0, here)
    from python_types import generate as generate_types

    generate_types(schema, sdk)
    return operations


def stale(root: Path = ROOT) -> dict[str, list[str]]:
    """Every committed generated file that differs from what the code generates now."""
    with tempfile.TemporaryDirectory() as temp:
        generate(Path(temp))
        found = {}
        for name in GENERATED:
            fresh = (Path(temp) / name).read_text()
            path = root / name
            current = path.read_text() if path.exists() else ""
            if fresh != current:
                found[name] = list(
                    difflib.unified_diff(
                        current.splitlines(), fresh.splitlines(), name, name + " (generated)", n=1, lineterm=""
                    )
                )
        return found


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="compare instead of writing")
    args = parser.parse_args()
    if args.check:
        found = stale()
        for name, diff in found.items():
            print(f"stale: {name}", file=sys.stderr)
            print("\n".join(diff[:40]), file=sys.stderr)
        if found:
            print("Run python scripts/generate_contract.py and commit the result.", file=sys.stderr)
            raise SystemExit(1)
        print("Generated contract files are current")
        return
    print(f"Generated {len(generate(ROOT))} operations")


if __name__ == "__main__":
    main()
